
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('users').del(),

    // Inserts seed entries
    knex('users').insert({userID: 11, name: 'Tony Luisi', email: 'buckey@gmail.com', hashedPassword: 'qwieu838', gender: 'male', aboutMe:'Hi all! I am on holiday from the UK touring around New Zealand, message me to join in on my adventures.  Expect lots of detours to along the way, music and lively debate.  Happy to share with single peron or a couple.  Message me.', driverLicenceDuration: '4', age: '25', urlImage: "https://avatars1.githubusercontent.com/u/13082144?v=3&s=460" }),
    knex('users').insert({userID: 12, name: 'Maxine Ellah', email: 'tony@gmail.com', hashedPassword: 'ewfkjuw', gender: 'female', aboutMe: 'Tall balding ginger, left handed, 115kg and most of that is ego.  Im also colour bind, so do not get too excited if I skip traffic lights.  I love to sing along to the radio, I recommend you sing along (it will be a really long trip if you do not.  Am happy to make regular coffee stops, just shout.  No dogs or cats or rabbits...', driverLicenceDuration: '10', age: '32', urlImage: "https://avatars2.githubusercontent.com/u/16638694?v=3&s=460" }),
    knex('users').insert({userID: 13, name: 'Natasha Duggan ', email: 'natasha@gmail.com', hashedPassword: 'edfkjuw', gender: 'female', aboutMe: 'I travel a lot for work and make this trip at least once a week.  Its long, its boring and I would love some company.  Would prefer a single passenger but its not deal breaker.  I love Country Music (my guilty pleasure), so prepare to listen to Blake Shelton and Tim McGraw for the entire trip, promise you will love it.', driverLicenceDuration: '12', age: '36', urlImage: "https://avatars2.githubusercontent.com/u/15882785?v=3&s=460"}),
    knex('users').insert({userID: 14, name: 'Wanda Laurent', email: 'wanda@gmail.com', hashedPassword: '34fkjuw', gender: 'female', aboutMe: 'I travel a lot for work and make this trip at least once a week.  Its long, its boring and I would love some company.  Would prefer a single passenger but its not deal breaker.  I love Country Music (my guilty pleasure), so prepare to listen to Blake Shelton and Tim McGraw for the entire trip, promise you will love it.', driverLicenceDuration: '10', age: '32', urlImage: "http://mclaughlinlaw.org/wp-content/uploads/2013/03/Elizabeth-Resized-470x376.jpg"}),
    knex('users').insert({userID: 15, name: 'Clint Davies', email: 'clint@gmail.com', hashedPassword: 'ewf567uw', gender: 'male', aboutMe:'Hi all! I am on holiday from the UK touring around New Zealand, message me to join in on my adventures.  Expect lots of detours to along the way, music and lively debate.  Happy to share with single peron or a couple.  Message me.', driverLicenceDuration: '4', age: '35', urlImage:"http://profiles.murdoch.edu.au/myprofile/guy-curtis/files/userphoto/228.jpg"}),
    knex('users').insert({userID: 16, name: 'Challa Nichols', email: 'challa@gmail.com', hashedPassword: 'wekjuw', gender: 'other', aboutMe:'Travelling through NZ and stopping at all the best mountain bike spots! Message me to join in on my adventures.  Expect lots of detours to along the way, there is room for a bike too if you want to join me on a few tracks..  Happy to share with single peron or a couple.  Message me.', driverLicenceDuration: '4', age: '25', urlImage:"http://images.derstandard.at/t/12/2011/09/20/1316396877774.jpg"}),
    knex('users').insert({userID: 17, name: 'Tina Ramsey', email: 'tina@gmail.com', hashedPassword: 'ewfkjcf3', gender: 'female', aboutMe: 'I travel a lot for work and make this trip at least once a week.  Its long, its boring and I would love some company.  Would prefer a single passenger but its not deal breaker.  I love Country Music (my guilty pleasure), so prepare to listen to Blake Shelton and Tim McGraw for the entire trip, promise you will love it.', driverLicenceDuration: '12', age: '36', urlImage: "https://pbs.twimg.com/profile_images/533965329211617280/Zxf1LzF8.jpeg" }),
    knex('users').insert({userID: 10, name: 'name_test', email: 'email_test', hashedPassword: 'ewfkjcf3', gender: '..', aboutMe: '..', driverLicenceDuration: '1', age: '1', urlImage: "https://pbs.twimg.com/profile_images/533965329211617280/Zxf1LzF8.jpeg" }),
    knex('users').insert({userID: 18, name: 'Tamati Eeden', email: 'tamati@gmail.com', hashedPassword: 'qw3kjuw', gender: 'male', aboutMe: 'Travel for work so used to doing long hauls. Would love to come the company on these trips.  Looking for friendly chatty people', driverLicenceDuration: '20', age: '45', urlImage: "https://static2.stuff.co.nz/1393626575/287/9779287.jpg"})
  );
};
